dependencies = []
incompatibilities = []

[metadata]
id = "senyksia.spiderheck.infinitefriends"
version = "0.3.1"
title = "InfiniteFriends"
description = "Multiplayer beyond 4 people"
authors = [
    "senyksia"
]
game_version = 1.6
